steps:
  - name: gcr.io/cloud-builders/git
    args: ["clone", "https://github.com/YuanZheng0125/2020portfolio.git"]
  - name: "gcr.io/cloud-builders/gsutil"
    args:
      [
        "-h",
        "-m",
        "cp",
        "-r",
        "2020portfolio/dist/*",
        "gs://www.yzcanvas.com/",
      ]
